local QBCore = exports['qb-core']:GetCoreObject()

if Config.UseBlips then
  CreateThread(function()
    FPBlip = AddBlipForCoord(FoodProcessor.coords)
    SetBlipSprite (FPBlip, FoodProcessor.SetBlipSprite)
    SetBlipDisplay(FPBlip, FoodProcessor.SetBlipDisplay)
    SetBlipScale  (FPBlip, FoodProcessor.SetBlipScale)
    SetBlipAsShortRange(FPBlip, true)
    SetBlipColour(FPBlip, FoodProcessor.SetBlipColour)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName(FoodProcessor.BlipLabel)
    EndTextCommandSetBlipName(FPBlip)
  end)

  CreateThread(function()
    DPBLIP = AddBlipForCoord(DairyProcessor.coords)
    SetBlipSprite (DPBLIP, DairyProcessor.SetBlipSprite)
    SetBlipDisplay(DPBLIP, DairyProcessor.SetBlipDisplay)
    SetBlipScale  (DPBLIP, DairyProcessor.SetBlipScale)
    SetBlipAsShortRange(DPBLIP, true)
    SetBlipColour(DPBLIP, DairyProcessor.SetBlipColour)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName(DairyProcessor.BlipLabel)
    EndTextCommandSetBlipName(DPBLIP)
  end)

  CreateThread(function()
    SFBLIP = AddBlipForCoord(Seller.coords)
    SetBlipSprite (SFBLIP, Seller.SetBlipSprite)
    SetBlipDisplay(SFBLIP, Seller.SetBlipDisplay)
    SetBlipScale  (SFBLIP, Seller.SetBlipScale)
    SetBlipAsShortRange(SFBLIP, true)
    SetBlipColour(SFBLIP, Seller.SetBlipColour)
    BeginTextCommandSetBlipName("STRING")
    AddTextComponentSubstringPlayerName(Seller.BlipLabel)
    EndTextCommandSetBlipName(SFBLIP)
  end)
end